### PR TITLE
Reducing layers & fixing reports from hadolint

### PR DESCRIPTION
**Pull request by fbartels**
Hi,

I've ran the Dockerfile through Hadolint and fixed most of the recommendations (the one I ignored for now is that one not to use apt directly). I also reduced the layers in the builder step since this was giving me 404 messages since apt update and install were in different layers.

### CODE REVIEW

**Comment by danielguerra69** [comment]
I'm not sure this change is needed. I have had a lot off 404 messages and solved it with using :
docker build --no-cache --rm -t termserv .

**Comment by danielguerra69** [comment]
Hub docker is doing a build test. Just a sec o.k.

**Comment by fbartels** [comment]
Yes, building with --no-cache would indeed solve this as well. but by moving apt update and apt install into the same step you won't ever have to need to force a package list update with --no-cache

**Comment by danielguerra69** [comment]
It build well on the hub

**Pull request merged**
