### PR TITLE
Create debs and Install (really) the xrdp

### PR DESCRIPTION
**Pull request by comio**
Hi Daniel,

I just reworked the Dockerfile. I noticed that in your, we build the xrdp from sources... but we don't install anything from builder to target image.

In this PR I create deb files from xrdp and xorgxrdp sources (using debian dir from 19.04) and copy&install into the target container.

I briefly tested on my system and it seems to work (TM).

ciao

luigi

### CODE REVIEW

**Comment by fbartels** [comment]
Hi @comio,

with this change merged my container fails to build with the following error:

```
# Policy
find debian/xrdp/ -name \*.la -print0 | xargs -0 rm -f --
find debian/xrdp/usr/lib/ -name \*.a -print0 | \
    xargs -0 strip --strip-debug -R .comment --
make[1]: Leaving directory '/tmp/xrdp-0.9.10'
   dh_install
chown: invalid group: 'root:xrdp'
dh_install: debian/xrdp.install (executable config) returned exit code 1
debian/rules:41: recipe for target 'binary' failed
make: *** [binary] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
ERROR: Service 'terminalserver' failed to build: The command '/bin/sh -c dpkg-buildpackage -rfakeroot -uc -b' returned a non-zero code: 2
```

**Comment by danielguerra69** [comment]
groups are added in bin/docker-entrypoint. Im not sure if the deb package creates group xrdp

**Comment by comio** [comment]
Hi @fbartels ,

I'm sorry but I cannot reproduce.

My steps:
```
git clone ...
cd ubuntu-xrdp
docker build . --tag mytag
```
Can you provide your complete log and information about your build environment?

ciao

luigi

**Comment by fbartels** [comment]
Hi @comio,

yes it feels a bit strange. The system where I see this is a Synology Diskstation and here I am simply running `docker-compose build`. I have since then also tried to run the build on an Ubuntu 16.04 system and there it succeeds as well.

The complete output from the synology system is https://paste.9wd.eu/urafesemap

**Comment by danielguerra69** [comment]
and docker-compose build --no-cache ???

**Comment by fbartels** [comment]
here with --no-cache: https://paste.9wd.eu/ekecesufum

**Comment by danielguerra69** [comment]
This is the output from yesterdays commits from @comio on hub.docker.com
# Policy
find debian/xrdp/ -name \*.la -print0 | xargs -0 rm -f --
find debian/xrdp/usr/lib/ -name \*.a -print0 | \
xargs -0 strip --strip-debug -R .comment --
make[1]: Leaving directory '/tmp/xrdp-0.9.10'
dh_install
dh_installdocs
debian/rules override_dh_installchangelogs
make[1]: Entering directory '/tmp/xrdp-0.9.10'
dh_installchangelogs -pxrdp -- NEWS.md
dh_installchangelogs --remaining-packages
dh_installchangelogs: No packages to build. Architecture mismatch: amd64, want: any
make[1]: Leaving directory '/tmp/xrdp-0.9.10'
dh_installman
debian/rules override_dh_installinit
make[1]: Entering directory '/tmp/xrdp-0.9.10'
dh_installinit --no-restart-on-upgrade

**Pull request merged**
